### ISSUE TITLE
full link ID   based on TLS ?

### ISSUE THREAD

**Issue by antsbean** [huandu/go-tls#4]
In order to achieve full link ID tracking, based on TLS in go, in order to avoid function calls need to pass the context param .In the same coroutine, it is OK to get the link ID according to the coroutine ID, but how can one coroutine start another coroutine without obvious the passing link ID?

**Comment by huandu** [comment]
I guess you are asking for a feature like "goroutine ID inherence", which requires a child goroutine knows the information of its parent. It's not possible to implement it right now from my understanding.

It's recommended to use `Context` explicitly instead of using such hack way to implement full link ID tracking. The hack way is so fragile.
